### ISSUE TITLE
Keyboard tab order issue

### ISSUE THREAD

**Issue by Malvoz** [clavijojuan/L.cascadeButtons#1]
I noticed a keyboard issue:

1. Go to https://vibrant-perlman-43d7a4.netlify.app/
2. <kbd>tab</kbd> 5 times and press <kbd>enter</kbd>
3. <kbd>tab</kbd> 1 time

**Expected:**

The first button in the expanded list should be focused

**Result:**

The button in the next `div` is focused instead

**Comment by Malvoz** [comment]
> **Expected:**
>
> The first button in the expanded list should be focused

I now noticed the "buttons" in the list aren't actually buttons, just `<li>`s styled as such.

**Comment by clavijojuan** [comment]
Hi.

Do you think I should change li to button?

**Comment by Malvoz** [comment]
Yes, otherwise keyboard users can't use them. 😋

Then the DOM order would have to be changed, so that the list comes after the button that expanded it (to fix the keyboard tab _order_ issue).

**Comment by clavijojuan** [comment]
Hi @Malvoz, sorry for being late. Now it's fixed. Please let me know if works correctly (see demo).

Thanks you for make me improve this plugin 👍

**Comment by Malvoz** [comment]
No worries, there's no rush. Looks good with the tab order, and the inner buttons now use `<button>`, nice!

**Comment by clavijojuan** [comment]
👍  Thanks
