### ISSUE TITLE
Use `type="button"` to prevent unintended form submissions

### ISSUE THREAD

**Issue by Malvoz** [clavijojuan/L.cascadeButtons#2]
**Problem:**

If a Leaflet map is used inside a `<form>` with this plugin, the `<button>`s will submit that form.

**Solution:**

This can be prevented if `type="button"` is added to the button elements by default.

**Comment by clavijojuan** [comment]
Hi @Malvoz, how are you?

Fixed. Let me know if works correctly.

Thanks you.

**Comment by Malvoz** [comment]
@clavijojuan I'm good thanks, I hope you are as well.

> Fixed. Let me know if works correctly.

I haven't used the plugin, I just discovered it through your PR submission.

To be a bit more clear why `type="button"` is needed; the default of `<button>` without `type` is `"submit"`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type

Feel free to close this issue, since you've fixed it. Thanks!

**Comment by clavijojuan** [comment]
Thanks you
