### ISSUE TITLE
Screen reader issue

### ISSUE THREAD

**Issue by Malvoz** [clavijojuan/L.cascadeButtons#3]
**Problem:**

People that use screen readers and can't see the UI wont know that there are new content available after pressing <kbd>enter</kbd> to expand the cascade buttons.

**Solution:**

Use `aria-expanded="false"` on the buttons when the button list is collapsed, and `aria-expanded="true"` when the button list is expanded.

---

More info: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

**Comment by clavijojuan** [comment]
Hi @Malvoz,

Fixed 👍 

Thank you
